version: 1.0.{build}

image:
  - Visual Studio 2019
  - Visual Studio 2022

clone_folder: C:\projects\source
clone_depth: 1

environment:
  matrix:
    - generator: "Visual Studio 16 2019"
init:
  - cmd: echo "%image%"
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\%image%\Community\VC\Auxiliary\Build\vcvars64.bat"

before_build:
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

build_script:
  - cmd: echo "%image%"
  - cmd: echo "%generator%"
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G "%generator%" -DCMAKE_BUILD_TYPE=Debug ..
  - cmd: cmake --build . --config "Debug"

test_script:
  - cmd: ctest -C Debug

